- name: Update Repositories
  apt: update_cache=yes
  become_user: root
  changed_when: False

- name: Install System Packages
  become_user: root
  apt:
    name: 
      - build-essential
      - ccache
      - cmake
      - curl
      - dconf-editor
      - direnv
      - gettext
      - golang
      - htop
      - libevent-dev
      - libpthread-stubs0-dev
      - libsqlite3-dev
      - libtool
      - libtool-bin
      - lsof
      - lua5.1
      - neofetch
      - ninja-build
      - pkg-config
      - python
      - python3-dev
      - python3-pip
      - python3-venv
      - python3-virtualenv
      - rename
      - silversearcher-ag
      - tree
      - unzip
      - webp
      - zsh
      - tar
      - wget
      - bat
      - nodejs
      - npm
      - fish
      - shellcheck
      - docker
      - ripgrep
      - tmux


- name: Check if bat is in correct place
  stat:
    path: "{{ lookup('env', 'HOME') }}/.local/bin/bat"
  register: bat_exists

- name: Fix bat location
  shell: mkdir -p {{ lookup('env', 'HOME') }}/.local/bin && ln -s /usr/bin/batcat {{ lookup('env', 'HOME') }}/.local/bin/bat
  when: bat_exists is not defined
