---
- hosts: ubuntu
  gather_facts: true
  become: true
  roles:
    - role: prereq
    - role: terminal
    - role: ubuntu

- hosts: arch
  gather_facts: true
  become: true
  roles:
    - role: prereq
    - role: terminal
    - role: arch

- hosts: terminal
  gather_facts: true
  become: true
  roles:
    - role: prereq
    - role: terminal
