---

- name: check is tmux installed
  shell: command -v tmux
  register: tmux_exists
  ignore_errors: true

- name: Install tmux
  when: tmux_exists is failed
  become_user: root
  shell: |
    TMUX_VERSION=$(curl --silent https://github.com/tmux/tmux/releases/latest | tr -d '"' | sed 's/^.*tag\///g' | sed 's/>.*$//g' | sed 's/^v//')
    wget https://github.com/tmux/tmux/releases/download/${TMUX_VERSION}/tmux-${TMUX_VERSION}.tar.gz -O- -q | tar -zxf - -C /tmp
    cd /tmp/tmux-${TMUX_VERSION}
    sudo ./configure
    sudo make
    sudo make install

- name: Check if Tmux Plugin Manager is installed
  stat:
    path: "{{ lookup('env', 'HOME') }}/.tmux/plugins/"
  register: tmux_plugin_path

- name: Create directory for Tmux Plugin Manager
  file:
    path:  "{{ lookup('env','HOME') }}/.tmux/plugins"
    state: directory
  when: tmux_plugin_path is not defined
      
- name: Download Tmux Plugin Manager
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ lookup('env','HOME') }}/.tmux/plugins/tpm"
    # owner: "{{ansible_user}}"
    # group: "{{ansible_user}}"
    # mode: 0755
    clone: true
    update: true
  when: tmux_plugin_path is not defined
