---
- name: Check is zsh installed
  shell: command -v zsh
  register: zsh_exists
  ignore_errors: true

- name: Change shell to zsh
  become_user: root
  shell: usermod --shell /usr/bin/zsh {{ ansible_user }}
  when: zsh_exists is not failed



- name: Check if zsh-autosuggestions is installed
  stat:
    path: "{{ lookup('env', 'HOME') }}/.zsh/plugins/zsh-autosuggestions"
  register: zshautosuggestions_path

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "{{ lookup('env', 'HOME') }}/.zsh/plugins/zsh-autosuggestions"
  when: zshautosuggestions_path.stat.islnk is not defined



- name: Check if zsh-history-substring-search is installed
  stat:
    path: "{{ lookup('env', 'HOME') }}/.zsh/plugins/zsh-history-substring-search"
  register: zsh_history_substring_search_path

- name: Install zsh-history-substring-search
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-history-substring-search.git'
    dest: "{{ lookup('env', 'HOME') }}/.zsh/plugins/zsh-history-substring-search"
  when: zsh_history_substring_search_path.stat.islnk is not defined






- name: Check if zsh-syntax-highlighting is installed
  stat:
    path: "{{ lookup('env', 'HOME') }}/.zsh/plugins/zsh-syntax-highlighting"
  register: zsh_syntax_highlighting_exists

- name: Install zsh-syntax-highlighting
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    dest: "{{ lookup('env', 'HOME') }}/.zsh/plugins/zsh-syntax-highlighting"
  when: zsh_syntax_highlighting_exists.stat.islnk is not defined





- name: Check if starship is installed
  shell: command -v starship
  register: starship_exists
  ignore_errors: true

- name: Install Starship
  shell: "curl -sS https://starship.rs/install.sh -y| sh"
  when: starship_exists is failed




